/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import type { Mesh } from 'three'
import { useControls } from 'leva'

export function ComputerModel(props) {
  const { nodes, materials } = useGLTF('./models/computer.glb')
  const mesh = useRef<Mesh>(null)
  const [rotationX, setRotationX] = useState<number>(0)
  const [rotationY, setRotationY] = useState<number>(0)
  useEffect(() => {
    document.addEventListener('mousemove', (event) => {
      setRotationY(((event.clientX - window.innerWidth / 2) * 1) / window.innerWidth)
      setRotationX(((event.clientY - window.innerHeight / 2) * 0.1) / window.innerHeight)
    })
  }, [])
  useFrame(({ clock }) => {
    mesh.current.rotation.y = rotationY
    mesh.current.rotation.x = rotationX
  })
  return (
    <group {...props} dispose={null} ref={mesh}>
      <mesh
        name="stand001"
        castShadow
        receiveShadow
        geometry={nodes.stand001.geometry}
        material={materials.stand}
        position={[-0.08, 0.65, -0.69]}
      />
      <mesh
        name="bezel001"
        castShadow
        receiveShadow
        geometry={nodes.bezel001.geometry}
        material={materials.bezel}
        position={[-0.08, 1.77, -1.06]}
      />
      <mesh
        name="screen001"
        castShadow
        receiveShadow
        geometry={nodes.screen001.geometry}
        material={materials.screen}
        position={[-0.08, 1.77, 0.03]}
      />
      <mesh
        name="controlPanel001"
        castShadow
        receiveShadow
        geometry={nodes.controlPanel001.geometry}
        material={materials['Material.001']}
        position={[-0.08, 0.47, 0.25]}
      />
      <mesh
        name="leverHead001"
        castShadow
        receiveShadow
        geometry={nodes.leverHead001.geometry}
        material={materials.leverHead}
        position={[0.45, 0.85, 0.57]}
      />
      <mesh
        name="lever001"
        castShadow
        receiveShadow
        geometry={nodes.lever001.geometry}
        material={materials['metal.001']}
        position={[0.45, 0.58, 0.54]}
      />
      <group name="leverBase001" position={[0.45, 0.58, 0.54]}>
        <mesh
          name="Cube018"
          castShadow
          receiveShadow
          geometry={nodes.Cube018.geometry}
          material={materials.metal}
        />
        <mesh
          name="Cube018_1"
          castShadow
          receiveShadow
          geometry={nodes.Cube018_1.geometry}
          material={materials.black}
        />
      </group>
      <mesh
        name="button001"
        castShadow
        receiveShadow
        geometry={nodes.button001.geometry}
        material={materials.button}
        position={[0.45, 0.65, 0.19]}
      />
      <mesh
        name="base001"
        castShadow
        receiveShadow
        geometry={nodes.base001.geometry}
        material={materials.base}
        position={[-0.08, 0.34, -0.27]}
      />
      <mesh
        name="monitor001"
        castShadow
        receiveShadow
        geometry={nodes.monitor001.geometry}
        material={materials.monitor}
        position={[-0.08, 1.77, -1.06]}
      />
      <mesh
        name="keycaps001"
        castShadow
        receiveShadow
        geometry={nodes.keycaps001.geometry}
        material={materials.keycaps}
        position={[-0.57, 0.71, 0.11]}
      />
      <mesh
        name="Text001"
        castShadow
        receiveShadow
        geometry={nodes.Text001.geometry}
        material={materials.keycaps}
        position={[-0.78, 0.28, 0.86]}
      />
    </group>
  )
}

useGLTF.preload('/models/computer.glb')
